steps:
# Step 1: Download and execute the installer script
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'apt-get update && apt-get install -y curl && curl --proto "=https" --tlsv1.2 -LsSf https://github.com/mpeterdev/bos-loader/releases/download/v0.7.1/bos-loader-v0.7.1-installer.sh | sh'
  id: 'download-and-install-bos-loader'
# Step 2: Modify the JSON file using jq
- name: 'gcr.io/cloud-builders/jq'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      jq 'del(.REPL_ACCOUNT)' replacements.mainnet.json > temp.json
      mv temp.json replacements.mainnet.json
  id: 'modify-json'

# Step 3: Make bos-loader executable
- name: 'gcr.io/cloud-builders/bash'
  args: ['chmod', '+x', 'bos-loader']
  id: 'make-bos-loader-executable'

# Step 4: Execute bos-loader
- name: 'gcr.io/cloud-builders/bash'
  args: ['bos-loader', '-p', 'src/', '-r', 'replacements.mainnet.json', 'near']
  id: 'execute-bos-loader'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/bos-components-service', '.']
  id: 'docker-build'

# Step 6: Push the Docker image to Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bos-components-service']
  id: 'docker-push'

# Step 7: Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'bos-components-service', '--image', 'gcr.io/$PROJECT_ID/my-service-image', '--region', 'YOUR_REGION', '--platform', 'managed', '--allow-unauthenticated']
  id: 'deploy-to-cloud-run'
